version: '3'

services:
  server:
    container_name: server
    build: ./nginx
    volumes:
    - ./src:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8081:80"
    restart: always
    depends_on:
      - app
    networks:  
      - app
      
  app:
    container_name: app
    build: ./php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:  
      - app

  db:
    container_name: db
    restart: always
    build: ./mysql
    volumes:
    - mysql_data:/var/lib/mysql
    env_file:
      - ./mysql/.env
    ports:
      - 3307:3306
    networks:  
      - app

networks:
  app:
volumes: 
  mysql_data: